const allThemeData={1:theme1,2:theme2,3:theme3,4:theme4,5:theme5,6:theme6,7:theme7};
function currentData(){return allThemeData[currentTheme];}



let currentDevice='',currentTheme=1,quizIndex=0,quizScore=0;
function showOnly(id){['home','themes','actions','coach'].forEach(x=>document.getElementById(x).classList.toggle('hidden',x!==id));}
function selectDevice(device,icon){currentDevice=device;document.getElementById('themeDeviceName').textContent=device;document.getElementById('themeDeviceIcon').textContent=icon;renderThemes();showOnly('themes')}
function goHome(){showOnly('home')}
function backToThemes(){showOnly('themes')}
function backToActions(){showOnly('actions')}
function renderThemes(){const grid=document.getElementById('themeGrid');grid.innerHTML='';if(currentDevice!=='iPhone'){grid.innerHTML=`<div class="card"><div class="icon">🚧</div><div><h3>Deze module komt later</h3><p>We werken nu eerst de iPhone 1-module volledig uit.</p></div></div>`;return}themes.forEach(t=>{const el=document.createElement('div');el.className='card'+(t.ready?'':' locked');el.innerHTML=`<div class="icon">${t.icon}</div><div><h3>${t.title}</h3><p>${t.desc}</p><span class="badge ${t.ready?'ready':''}">${t.ready?'Beschikbaar':'Binnenkort'}</span></div>`;if(t.ready)el.onclick=()=>openTheme(t.id);grid.appendChild(el)})}
function openTheme(id){currentTheme=id;const t=themes.find(x=>x.id===id);document.getElementById('themeTitle').textContent=t.title;document.getElementById('themeIntro').textContent=currentData().intro;showOnly('actions')}
function openChatGPT(){window.open('https://chatgpt.com/g/g-69c0f5356b60819193fa4c3a42cf24de-cvo-lbc-apple-classes-iphone-1','_blank','noopener,noreferrer');}
function openMode(mode){showOnly('coach');const title={learn:'Leren',practice:'Oefenen',help:'Hulp vragen',quiz:'Test jezelf'}[mode];const icon={learn:'📘',practice:'🧩',help:'💬',quiz:'✅'}[mode];document.getElementById('coachTitle').textContent=`iPhone • ${title}`;document.getElementById('coachModeIcon').textContent=icon;if(mode==='learn')renderLessons();if(mode==='practice')renderPractice();if(mode==='help')renderHelp();if(mode==='quiz'){quizIndex=0;quizScore=0;renderQuiz()}}
function renderLessons(){const b=document.getElementById('coachBody');b.innerHTML=`<div class="bubble"><strong>${themes.find(x=>x.id===currentTheme).title}</strong><br>Kies een korte les. Je kunt ze in volgorde volgen of meteen naar een onderdeel gaan.</div><div class="lesson-list" id="lessonList"></div>`;const list=document.getElementById('lessonList');currentData().lessons.forEach((l,i)=>{const d=document.createElement('div');d.className='lesson-item';d.innerHTML=`<strong>${l.title}</strong><span>${l.summary}</span>`;d.onclick=()=>showLesson(i);list.appendChild(d)})}
function showLesson(i){const l=currentData().lessons[i];document.getElementById('coachBody').innerHTML=`<button class="secondary" onclick="renderLessons()">← Alle lessen</button><h2>${l.title}</h2><p class="small">${l.summary}</p>${l.html}<div class="choices">${i>0?`<button class="secondary" onclick="showLesson(${i-1})">Vorige</button>`:''}${i<currentData().lessons.length-1?`<button class="primary" onclick="showLesson(${i+1})">Volgende les</button>`:`<button class="primary" onclick="renderPractice()">Ga oefenen</button>`}</div>`}
function renderPractice(){const b=document.getElementById('coachBody');b.innerHTML=`<div class="bubble"><strong>Nu jij.</strong> Voer de opdrachten uit op je eigen iPhone. Je mag rustig opnieuw proberen.</div><div class="lesson-list" id="exerciseList"></div>`;const list=document.getElementById('exerciseList');currentData().exercises.forEach((e,i)=>{const d=document.createElement('div');d.className='lesson-item';d.innerHTML=`<strong>${e.title}</strong><span>${e.text}</span><div class="choices"><button class="success" onclick="event.stopPropagation();markDone(this)">Gelukt</button><button class="secondary" onclick="event.stopPropagation();showExerciseHint(${i})">Nog niet gelukt</button></div>`;list.appendChild(d)})}
function markDone(btn){btn.textContent='✓ Gelukt';btn.disabled=true}
function showExerciseHint(i){const e=currentData().exercises[i];if(e.hint){alert(e.hint);return}const hints=['Kijk aan de linker- en rechterzijde van je iPhone. Begin met de twee langwerpige volumeknoppen en zoek daarna de zijknop.','Open bijvoorbeeld Foto’s. Met Face ID veeg je omhoog vanaf de onderrand; met een thuisknop druk je één keer op die knop.','Met Face ID: veeg omhoog vanaf de onderrand, stop in het midden en til je vinger op. Met thuisknop: druk twee keer.','Open één foto. Zet twee vingers dicht bij elkaar op de foto en beweeg ze uit elkaar.','Veeg op een iPhone met Face ID vanaf de rechterbovenhoek naar beneden.'];alert(hints[i]||'Probeer de opdracht stap voor stap opnieuw.')}
function renderHelp(){const b=document.getElementById('coachBody');b.innerHTML=`<div class="bubble">Waar loop je vast? Kies de situatie die het dichtst in de buurt komt.</div><div class="choices" id="helpChoices"></div><div id="helpAnswer" style="margin-top:18px"></div>`;const c=document.getElementById('helpChoices');currentData().help.forEach((h,i)=>{const btn=document.createElement('button');btn.className='secondary';btn.textContent=h.q;btn.onclick=()=>document.getElementById('helpAnswer').innerHTML=`<div class="bubble"><strong>${h.q}</strong><br>${h.a}</div>`;c.appendChild(btn)})}
function renderQuiz(){const data=currentData(),q=data.quiz[quizIndex],b=document.getElementById('coachBody');if(!q){const pct=Math.round(quizScore/data.quiz.length*100);b.innerHTML=`<div class="bubble"><strong>Test klaar.</strong><br>Je behaalde ${quizScore} op ${data.quiz.length} (${pct}%).</div><div class="tip">${pct>=75?'Mooi. Je beheerst de basis van dit thema.':'Herhaal vooral de onderdelen die nog onzeker voelen en probeer daarna opnieuw.'}</div><div class="choices"><button class="primary" onclick="quizIndex=0;quizScore=0;renderQuiz()">Test opnieuw</button><button class="secondary" onclick="renderLessons()">Herhalen</button></div>`;return}const progress=Math.round(quizIndex/data.quiz.length*100);b.innerHTML=`<div class="small">Vraag ${quizIndex+1} van ${data.quiz.length}</div><div class="progress"><div style="width:${progress}%"></div></div><h2>${q.q}</h2><div id="quizOpts"></div><div id="quizFeedback"></div>`;const opts=document.getElementById('quizOpts');q.opts.forEach((o,i)=>{const btn=document.createElement('button');btn.className='quiz-option';btn.textContent=o;btn.onclick=()=>answerQuiz(i,btn);opts.appendChild(btn)})}
function answerQuiz(i,btn){const data=currentData(),q=data.quiz[quizIndex];document.querySelectorAll('.quiz-option').forEach(x=>x.disabled=true);if(i===q.answer){quizScore++;btn.classList.add('correct');document.getElementById('quizFeedback').innerHTML='<div class="bubble">✓ Juist.</div>'}else{btn.classList.add('wrong');document.querySelectorAll('.quiz-option')[q.answer].classList.add('correct');document.getElementById('quizFeedback').innerHTML='<div class="bubble">Nog niet. Het juiste antwoord is aangeduid.</div>'}const next=document.createElement('button');next.className='primary';next.textContent=quizIndex===currentData().quiz.length-1?'Bekijk resultaat':'Volgende vraag';next.onclick=()=>{quizIndex++;renderQuiz()};document.getElementById('quizFeedback').appendChild(next)}

