const theme3={
 intro:'Maak je iPhone persoonlijker en begrijp de belangrijkste instellingen. Je leert zoeken in Instellingen, opslag controleren, tekst invoeren, het scherm aanpassen, geluiden beheren, meldingen bekijken en Niet storen gebruiken.',
 lessons:[
  {title:'1. Snel iets vinden in Instellingen',summary:'Gebruik zoeken in plaats van eindeloos scrollen.',html:`<div class="bubble">De app <strong>Instellingen</strong> bevat veel onderdelen. Je hoeft ze niet allemaal uit het hoofd te kennen.</div><div class="step">Open Instellingen en gebruik de zoekfunctie wanneer je een instelling niet meteen vindt.</div><div class="tip">Een goede iPhone-gebruiker hoeft niet alles te onthouden. Weten hoe je iets terugvindt is belangrijker.</div>`},
  {title:'2. Naam, softwareversie en opslag controleren',summary:'Belangrijke informatie over je eigen toestel.',html:`<div class="bubble">In de algemene instellingen kun je informatie over je iPhone bekijken, zoals de naam, softwareversie en opslagruimte.</div><div class="step">Zoek in Instellingen naar de naam of softwareversie van je iPhone.</div><div class="step">Bekijk bij <strong>iPhone-opslag</strong> hoeveel ruimte gebruikt wordt en welke categorieën veel plaats innemen.</div><div class="tip">Opslag kan onder andere gebruikt worden door apps, foto's, media, mail, berichten, iCloud Drive en systeembestanden.</div>`},
  {title:'3. Toetsenbord en tekstinvoer',summary:'Typen, corrigeren en het toetsenbord aanpassen.',html:`<div class="bubble">Je iPhone heeft instellingen voor het schermtoetsenbord en verschillende voorzieningen om tekst gemakkelijker in te voeren.</div><div class="step">Je kunt toetsenbordinstellingen wijzigen, naar een ander toetsenbord overschakelen en op ondersteunde situaties eenhandig typen gebruiken.</div><div class="step">Je kunt tekst selecteren en bewerken en het toetsenbord als trackpad gebruiken.</div>`},
  {title:'4. Dicteren',summary:'Tekst inspreken in plaats van typen.',html:`<div class="bubble">Met <strong>dicteren</strong> kun je tekst invoeren met je stem.</div><div class="step">Open een tekstveld en gebruik de dicteerfunctie op het toetsenbord.</div><div class="step">Spreek duidelijk. Je kunt ook leestekens toevoegen tijdens het dicteren.</div><div class="tip">Controleer na het dicteren altijd even of de tekst juist werd herkend.</div>`},
  {title:'5. Achtergrond en scherm aanpassen',summary:'Je iPhone persoonlijker en comfortabeler maken.',html:`<div class="bubble">Je kunt een afbeelding of eigen foto als achtergrond gebruiken voor het toegangsscherm, beginscherm of beide.</div><div class="step">Zoek in Instellingen naar <strong>Achtergrond</strong> om een andere achtergrond te kiezen.</div><div class="step">Je kunt ook helderheid, donkere modus, True Tone en Night Shift aanpassen.</div><div class="tip">Donkere modus gebruikt een donker kleurenschema. Night Shift verandert de kleurbalans van het scherm.</div>`},
  {title:'6. Schermstand, zoom en schermafbeeldingen',summary:'Weergave en vastleggen wat je op het scherm ziet.',html:`<div class="bubble">Je kunt de schermstand vergrendelen, de schermweergave vergroten en een foto of video van je scherm maken.</div><div class="step">Gebruik de rotatievergrendeling wanneer je niet wilt dat het scherm meedraait.</div><div class="step">Een <strong>schermafbeelding</strong> bewaart wat je op dat moment op je scherm ziet.</div><div class="step">Met een <strong>schermopname</strong> maak je een video van wat op het scherm gebeurt.</div>`},
  {title:'7. Volume, beltoon en trillingen',summary:'Begrijp welk geluid je aanpast.',html:`<div class="bubble">Je iPhone heeft verschillende soorten geluid: media, beltoon, meldingen en waarschuwingen.</div><div class="step">Via Instellingen → Horen en voelen of Geluiden kun je het volume voor beltoon en meldingen aanpassen.</div><div class="step">Via het bedieningspaneel kun je het volume snel wijzigen.</div><div class="tip">Wanneer het belsignaal stil staat, kunnen bepaalde geluiden zoals een wekker nog steeds hoorbaar zijn.</div>`},
  {title:'8. Meldingen bekijken en beheren',summary:'Grip krijgen op berichten van apps.',html:`<div class="bubble"><strong>Meldingen</strong> laten je weten dat er iets gebeurd is, bijvoorbeeld een bericht, gemiste oproep of e-mail.</div><div class="step">Bekijk je meldingen op één plek in het berichtencentrum.</div><div class="step">Je kunt op meldingen reageren, ze sluiten, wissen of beheren.</div><div class="tip">Niet elke app hoeft je voortdurend te onderbreken. Je kunt meldingen per app beheren.</div>`},
  {title:'9. Niet storen',summary:'Tijdelijk minder onderbrekingen.',html:`<div class="bubble">Met <strong>Niet storen</strong> kun je inkomende gesprekken, waarschuwingen en meldingen tijdelijk stilhouden.</div><div class="step">Je kunt Niet storen inschakelen en stille uren plannen.</div><div class="step">Je kunt uitzonderingen instellen, bijvoorbeeld voor bepaalde inkomende gesprekken of noodcontacten.</div><div class="tip">Niet storen betekent niet dat je iPhone uit staat. De meldingen worden vooral minder storend aangeboden volgens je instellingen.</div>`}
 ],
 exercises:[
  {title:'Oefening 1 • Zoek een instelling',text:'Open Instellingen en zoek naar “iPhone-opslag”. Open het gevonden onderdeel.',hint:'Open Instellingen en gebruik de zoekfunctie bovenaan. Typ “iPhone-opslag”.'},
  {title:'Oefening 2 • Bekijk je opslag',text:'Bekijk hoeveel opslagruimte je iPhone gebruikt. Zoek welke drie categorieën of apps het meeste ruimte innemen.',hint:'Ga naar Instellingen → Algemeen → iPhone-opslag of zoek naar “iPhone-opslag”.'},
  {title:'Oefening 3 • Dicteer een zin',text:'Open Notities of een ander tekstveld en dicteer de zin: “Vandaag oefen ik met mijn iPhone.” Controleer daarna de tekst.',hint:'Tik in een tekstveld zodat het toetsenbord verschijnt. Zoek de dicteerfunctie op het toetsenbord en spreek rustig.'},
  {title:'Oefening 4 • Pas je scherm aan',text:'Open de instellingen voor helderheid en verander de helderheid een beetje. Zet daarna de donkere modus kort aan en opnieuw uit.',hint:'Zoek in Instellingen naar “Beeldscherm” of “Donkere modus”. Je kunt helderheid ook via het bedieningspaneel wijzigen.'},
  {title:'Oefening 5 • Maak een schermafbeelding',text:'Maak een schermafbeelding van je beginscherm en zoek de afbeelding daarna terug in Foto’s.',hint:'De juiste knopcombinatie hangt af van je iPhone-model. Gebruik de methode die je in thema 1 voor jouw model hebt leren herkennen.'},
  {title:'Oefening 6 • Bekijk je meldingen',text:'Open het berichtencentrum en bekijk welke meldingen er staan. Wis alleen een melding die je zeker niet meer nodig hebt.',hint:'Veeg vanaf de bovenkant van het scherm omlaag om je recente meldingen te bekijken.'},
  {title:'Oefening 7 • Zoek Niet storen',text:'Zoek waar Niet storen ingesteld wordt. Bekijk welke opties je kunt aanpassen, maar wijzig nog niets dat je niet begrijpt.',hint:'Gebruik de zoekfunctie in Instellingen en typ “Niet storen”.'}
 ],
 help:[
  {q:'Ik vind een instelling niet',a:'Gebruik de zoekfunctie in de app Instellingen. Typ een herkenbaar woord, bijvoorbeeld “opslag”, “achtergrond”, “Bluetooth” of “Niet storen”.'},
  {q:'Mijn opslag is bijna vol',a:'Open iPhone-opslag en bekijk eerst welke categorieën en apps de meeste ruimte gebruiken. Verwijder niet zomaar iets. Bepaal eerst wat je herkent en wat je nog nodig hebt.'},
  {q:'Dicteren schrijft verkeerde woorden',a:'Spreek iets trager en duidelijker en controleer de tekst achteraf. Je kunt fouten daarna gewoon met het toetsenbord verbeteren.'},
  {q:'Mijn scherm draait steeds mee',a:'Controleer de schermstandvergrendeling. Als die ingeschakeld is, blijft de staande weergave vergrendeld.'},
  {q:'Mijn scherm is te donker',a:'Open het bedieningspaneel en pas de helderheid aan, of zoek in Instellingen naar helderheid. Controleer ook of donkere modus of Night Shift actief is als de weergave anders lijkt.'},
  {q:'Mijn beltoon is stil maar mijn wekker maakt toch geluid',a:'Dat kan normaal zijn. Volgens de cursus blijven onder andere het geluid van de wekker en bepaalde audioapps hoorbaar wanneer het belsignaal is uitgeschakeld.'},
  {q:'Ik krijg te veel meldingen',a:'Ga naar Instellingen en beheer Meldingen per app. Kies bewust van welke apps je meldingen wilt ontvangen.'},
  {q:'Ik wil even niet gestoord worden',a:'Gebruik Niet storen. Je kunt dit tijdelijk inschakelen en ook instellen welke oproepen of noodcontacten toch mogen doorkomen.'}
 ],
 quiz:[
  {q:'Wat is een handige manier om een instelling snel terug te vinden?',opts:['De zoekfunctie in Instellingen gebruiken','Alle apps verwijderen','De iPhone uitschakelen'],answer:0},
  {q:'Waar kijk je welke apps of categorieën veel opslag gebruiken?',opts:['iPhone-opslag','Wereldklok','FaceTime'],answer:0},
  {q:'Wat kun je met dicteren doen?',opts:['Tekst inspreken','Wifi uitschakelen','Een app verwijderen'],answer:0},
  {q:'Waarvoor gebruik je de donkere modus?',opts:['Een donker kleurenschema voor de weergave','Om mobiele data sneller te maken','Om contacten te verwijderen'],answer:0},
  {q:'Wat doet schermstandvergrendeling?',opts:['Voorkomt dat de schermweergave meedraait','Vergrendelt je simkaart','Blokkeert alle apps'],answer:0},
  {q:'Wat is een schermafbeelding?',opts:['Een foto van wat op je scherm staat','Een foto met de achtercamera','Een nieuwe achtergrond'],answer:0},
  {q:'Waar kun je het volume snel aanpassen terwijl je een app gebruikt?',opts:['In het bedieningspaneel','Alleen in Contacten','In Safari-geschiedenis'],answer:0},
  {q:'Wat kun je met meldingen doen?',opts:['Bekijken, erop reageren, sluiten, wissen en beheren','Alleen bekijken','Alleen afdrukken'],answer:0},
  {q:'Waarvoor dient Niet storen?',opts:['Om oproepen, waarschuwingen en meldingen tijdelijk stil te houden','Om opslagruimte vrij te maken','Om wifiwachtwoorden te veranderen'],answer:0},
  {q:'Kan een wekker nog geluid maken als het belsignaal uit staat?',opts:['Ja, dat kan','Nee, nooit','Alleen via Bluetooth'],answer:0}
 ]
};




