const theme2={
 intro:'Leer hoe je iPhone verbinding maakt met internet en andere apparaten. Je oefent met wifi, mobiele data, Bluetooth, persoonlijke hotspot en de netwerkregelaars in het bedieningspaneel.',
 lessons:[
  {title:'1. Wifi en mobiele data begrijpen',summary:'Twee manieren om met internet te verbinden.',html:`<div class="bubble">Je iPhone kan internet gebruiken via <strong>wifi</strong> of via het <strong>mobiele datanetwerk|/strong> van je aanbieder.</div><div class="step"><strong>Wifi:</strong> je maakt verbinding met een draadloos netwerk in de buurt.</div><div class="step"><strong>Mobiele data:</strong> je iPhone gebruikt het netwerk van je mobiele aanbieder wanneer geen geschikte wifi beschikbaar is.</div><div class="tip">Mobiele gegevensoverdracht kan afhankelijk van je abonnement kosten veroorzaken. Controleer dit bij je aanbieder.</div>`},
  {title:'2. Verbinden met een wifinetwerk',summary:'Een netwerk kiezen en het wachtwoord invoeren.',html:`<div class="bubble">Ga naar <strong>Instellingen → Wifi</strong> en zorg dat Wifi is ingeschakeld.</div><div class="step">Tik op het netwerk waarmee je wilt verbinden.</div><div class="step">Voer indien nodig de toegangscode in.</div><div class="step">Controleer de verbinding door bijvoorbeeld een webpagina in Safari te openen.</div><div class="tip">Je iPhone kan later automatisch opnieuw verbinding maken wanneer dat bekende netwerk weer in de buurt is.</div>`},
  {title:'3. Mobiele data controleren',summary:'Internet gebruiken zonder wifi.',html:`<div class="bubble">Als er geen wifi beschikbaar is, kan je iPhone verbinding maken met het mobiele datanetwerk van je aanbieder.</div><div class="step">Open <strong>Instellingen → Mobiel netwerk</strong>.</div><div class="step">Controleer of <strong>Mobiele data</strong> is ingeschakeld.</div><div class="tip">Bij Dual SIM kun je controleren welke lijn voor mobiele data is geselecteerd.</div>`},
  {title:'4. Bluetooth gebruiken',summary:'Verbinding met draadloze accessoires.',html:`<div class="bubble"><strong>Bluetooth</strong> gebruik je om verbinding te maken met apparaten zoals een koptelefoon, autoradio of draadloos toetsenbord.</div><div class="step">Ga naar <strong>Instellingen → Bluetooth</strong>.</div><div class="step">Schakel Bluetooth in en kies, wanneer zichtbaar, het apparaat waarmee je wilt verbinden.</div><div class="tip">Via het bedieningspaneel kun je Bluetooth-verbindingen tijdelijk verbreken. Bluetooth zelf wordt daarmee niet volledig uitgeschakeld.</div>`},
  {title:'5. Persoonlijke hotspot',summary:'De internetverbinding van je iPhone delen.',html:`<div class="bubble">Met <strong>Persoonlijke hotspot</strong> kun je de mobiele internetverbinding van je iPhone delen met een ander apparaat.</div><div class="step">Ga naar <strong>Instellingen → Mobiel netwerk → Persoonlijke hotspot</strong> of rechtstreeks naar <strong>Persoonlijke hotspot</strong>.</div><div class="step">Schakel Persoonlijke hotspot in.</div><div class="step">Gebruik op het andere apparaat de naam van je iPhone en het ingestelde wifiwachtwoord om te verbinden.</div><div class="tip">Niet elk abonnement ondersteunt Persoonlijke hotspot. Als de optie ontbreekt, kan je aanbieder hierover meer informatie geven.</div>`},
  {title:'6. Netwerkregelaars in het bedieningspaneel',summary:'Snel wifi, Bluetooth en mobiele data bekijken.',html:`<div class="bubble">Het <strong>bedieningspaneel</strong> geeft snelle toegang tot verschillende netwerkfuncties.</div><div class="step">Houd de groep met netwerkregelaars ingedrukt om meer opties te zien.</div><div class="step">Je vindt er onder andere vliegtuigmodus, mobiele data, wifi, Bluetooth en AirDrop.</div><div class="tip">Een tik op wifi of Bluetooth in het bedieningspaneel kan de huidige verbinding tijdelijk verbreken zonder de functie volledig uit te schakelen.</div>`},
  {title:'7. Verbinding controleren',summary:'Herkennen of je online bent.',html:`<div class="bubble">Bovenaan je iPhone zie je statussymbolen die informatie geven over je verbinding.</div><div class="step">Het wifisymbool toont dat je via wifi verbonden bent.</div><div class="step">Wanneer je mobiele netwerk beschikbaar is, kan je iPhone via mobiele data internet gebruiken.</div><div class="step">Een persoonlijke-hotspotsymbool of blauwe aanduiding kan aangeven dat een hotspot actief is.</div><div class="tip">Twijfel je? Open Safari en laad een webpagina. Dat is een eenvoudige praktische controle.</div>`}
 ],
 exercises:[
  {title:'Oefening 1 • Zoek je huidige verbinding',text:'Kijk bovenaan je iPhone. Ben je nu verbonden via wifi of gebruik je mobiele data?',hint:'Zoek naar het wifisymbool bovenaan. Zie je dat niet, open dan Instellingen → Wifi en controleer de status.'},
  {title:'Oefening 2 • Maak verbinding met wifi',text:'Open Instellingen → Wifi. Bekijk de beschikbare netwerken en maak verbinding met een netwerk waarvoor je toestemming hebt.',hint:'Controleer eerst of de schakelaar bij Wifi aan staat. Tik daarna op het juiste netwerk en voer indien nodig het wachtwoord in.'},
  {title:'Oefening 3 • Controleer mobiele data',text:'Open Instellingen → Mobiel netwerk en controleer of Mobiele data aan of uit staat. Verander niets als je niet zeker bent.',hint:'Zoek in Instellingen naar “Mobiel netwerk”. Bovenaan vind je de schakelaar voor Mobiele data.'},
  {title:'Oefening 4 • Ontdek Bluetooth',text:'Open Instellingen → Bluetooth. Bekijk welke apparaten al gekoppeld zijn of zichtbaar worden. Je hoeft niets nieuws te koppelen.',hint:'Bluetooth staat als apart onderdeel in Instellingen. Als je erop tikt, zie je de schakelaar en de apparatenlijst.'},
  {title:'Oefening 5 • Open de netwerkregelaars',text:'Open het bedieningspaneel en houd de netwerkkaart ingedrukt. Zoek wifi, Bluetooth, mobiele data en vliegtuigmodus.',hint:'Op een iPhone met Face ID veeg je vanaf de rechterbovenhoek naar beneden. Houd daarna de groep linksboven met netwerkknoppen even ingedrukt.'},
  {title:'Oefening 6 • Vind Persoonlijke hotspot',text:'Zoek in Instellingen waar Persoonlijke hotspot staat. Schakel de hotspot nog niet in als je hem niet nodig hebt.',hint:'Kijk bij Instellingen → Mobiel netwerk → Persoonlijke hotspot of zoek in Instellingen naar “Persoonlijke hotspot”.'}
 ],
 help:[
  {q:'Ik zie mijn wifinetwerk niet',a:'Controleer eerst of Wifi aan staat. Kijk of je dicht genoeg bij het netwerk bent. Staat het netwerk verborgen, dan kun je via “Ander” de netwerknaam en beveiligingsgegevens invoeren als je die kent.'},
  {q:'Mijn wifi is verbonden maar internet werkt niet',a:'Open Safari en probeer een webpagina. Werkt die niet, controleer dan of andere apparaten op hetzelfde netwerk internet hebben. Je iPhone kan wel met een wifinetwerk verbonden zijn terwijl dat netwerk zelf geen internetverbinding heeft.'},
  {q:'Ik weet niet of ik mobiele data gebruik',a:'Open Instellingen → Mobiel netwerk en controleer of Mobiele data is ingeschakeld. Bovenaan het scherm kun je ook aan de statussymbolen zien welke verbinding actief is.'},
  {q:'Bluetooth vindt mijn apparaat niet',a:'Controleer of Bluetooth op je iPhone aan staat en of het andere apparaat ingeschakeld en vindbaar is. Blijf tijdens het zoeken op het Bluetooth-scherm.'},
  {q:'Ik vind Persoonlijke hotspot niet',a:'Kijk bij Instellingen → Mobiel netwerk → Persoonlijke hotspot of rechtstreeks bij Persoonlijke hotspot. Als de optie ontbreekt, kan dit met je mobiele abonnement of aanbieder te maken hebben.'},
  {q:'Ik heb wifi uitgezet in het bedieningspaneel, maar het lijkt nog actief',a:'In het bedieningspaneel verbreek je de huidige wifiverbinding tijdelijk. Om Wifi volledig uit te schakelen ga je naar Instellingen → Wifi.'},
  {q:'Ik heb Bluetooth uitgezet in het bedieningspaneel, maar het staat nog aan',a:'Dat kan kloppen. Het bedieningspaneel verbreekt Bluetooth-verbindingen tijdelijk. Om Bluetooth volledig uit te schakelen ga je naar Instellingen → Bluetooth.'}
 ],
 quiz:[
  {q:'Welke twee hoofdmanieren gebruikt een iPhone om met internet te verbinden?',opts:['Wifi en mobiele data','Bluetooth en AirDrop','Camera en Safari'],answer:0},
  {q:'Waar maak je verbinding met een nieuw wifinetwerk?',opts:['Instellingen → Wifi','Foto’s → Albums','Klok → Timer'],answer:0},
  {q:'Wat kan je iPhone gebruiken als er geen wifi beschikbaar is?',opts:['Mobiele data van je aanbieder','Alleen Bluetooth','Alleen AirDrop'],answer:0},
  {q:'Waarvoor gebruik je Bluetooth vooral?',opts:['Voor verbinding met draadloze apparaten','Om foto’s te bewerken','Om een e-mail te schrijven'],answer:0},
  {q:'Wat doet Persoonlijke hotspot?',opts:['Deelt de mobiele internetverbinding met een ander apparaat','Verwijdert apps','Maakt automatisch foto’s'],answer:0},
  {q:'Wat gebeurt er als je wifi in het bedieningspaneel aantikt om de verbinding te verbreken?',opts:['De huidige verbinding wordt tijdelijk verbroken','Wifi wordt altijd volledig verwijderd','Je simkaart wordt uitgeschakeld'],answer:0},
  {q:'Waar kun je wifi volledig uitschakelen?',opts:['Instellingen → Wifi','Alleen in Foto’s','In de App Store'],answer:0},
  {q:'Wat is een eenvoudige manier om te controleren of je internetverbinding werkt?',opts:['Een webpagina openen in Safari','De iPhone schudden','Een screenshot maken'],answer:0}
 ]
};




